### ISSUE TITLE
[Admin] Obsługa błędów API w formularzach

### ISSUE THREAD

**Issue by mmiszy** [typeofweb/sklep#42]
- [ ] Obsługa błędów 400 w formularzach

**Comment by jundymek** [comment]
Michał. Tu chodzi tylko o jakiegoś toasta/message przy błędzie 400?

**Comment by mmiszy** [comment]
@jundymek niee. Chodzi o to, że gdy serwer zwraca błąd 400 to zawiera tam też listę pól które nie przeszły walidacji. Chcielibyśmy wykorzystać tę informację na froncie.

**Comment by jundymek** [comment]
Ok. Rozumiem. Jak mi się uda przysiąść w końcu na dłużej to się dopisze do tego taska i postaram się z tym pomęczyć.
